#!/bin/bash
#
# chkconfig: - 57 75
# description: flexbng service

VBRAS_DIR=/home/vBras
KVM_DIR=$VBRAS_DIR/kvm-imgs
start()
{
	echo $(date +%Y%m%d%H%M%S) >> /root/start.log
	echo "starting vm" >> /root/start.log
	$VBRAS_DIR/Step1.start-ovs.sh
	
}

stop()
{
#	echo $(date +%Y%m%d%H%M%S) >> /root/stop.log
#	echo "stop vm" >> /root/stop.log
	virsh shutdown all
	#wait for vm shutdown
	sleep 10
        ID=`ps -ef| grep -E ovs |grep -v 'grep'|awk '{print $2}'`
        for pid in $ID
        do
            kill -9 $pid
        done
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|force-reload)
	stop
	start
	;;
  *)
   echo $"Usage: $0 {start|stop|restart|force-reload}"
   exit 2
esac
while :
do
	sleep 1
done
